config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"	
  resources :product_categories
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prod_tag.rb
class ProdTag < ApplicationRecord
	belongs_to :tag
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prod_tags
  has_many :tags, through: :prod_tags
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :tag
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :prod_tags
  has_many :products, through: :prod_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: [:show, :edit, :update, :destroy]

  # GET /product_categories
  # GET /product_categories.json
  def index
    @product_categories = ProductCategory.all
  end

  # GET /product_categories/1
  # GET /product_categories/1.json
  def show
  end

  # GET /product_categories/new
  def new
    @product_category = ProductCategory.new
  end

  # GET /product_categories/1/edit
  def edit
  end

  # POST /product_categories
  # POST /product_categories.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to @product_category, notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1
  # PATCH/PUT /product_categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to @product_category, notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1
  # DELETE /product_categories/1.json
  def destroy
    @product_category.destroy
    respond_to do |format|
      format.html { redirect_to product_categories_url, notice: 'Product category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = ProductCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_category_params
      params.require(:product_category).permit(:name, :tag_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    binding.pry  
    if params["filter_products"] and !params["filter_products"]["catagory_id"].blank?
      @products = ProductCategory.find(params["filter_products"]["catagory_id"]).tag.products
    else  
      @products = Product.all.includes(:tags)
    end  
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create    
    @product = Product.new(name: product_params["name"], description: product_params["description"])
    respond_to do |format|
      if @product.save
        p_tags = product_params["p_tag"].split(",").map{ |p| p.strip }
        p_tags.each{ |p| t = Tag.find_or_create_by(name: p); @product.tags << t}

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :p_tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>ShopApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
     
    
    <li class="nav-item">
      <%= link_to "category", product_categories_path %>
    </li>
    <li class="nav-item">
      <%= link_to "products", products_path %>
    </li>  

    </nav>

    <%= yield %>
  </body>
</html>

app/views/product_categories/_form.html.erb
<%= form_with(model: product_category, local: true) do |form| %>
  <% if product_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

      <ul>
        <% product_category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= collection_select(:product_category, :tag_id, Tag.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_categories/edit.html.erb
<h1>Editing Product Category</h1>

<%= render 'form', product_category: @product_category %>

<%= link_to 'Show', @product_category %> |
<%= link_to 'Back', product_categories_path %>

app/views/product_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_categories.each do |product_category| %>
      <tr>
        <td><%= product_category.name %></td>
        <td><%= product_category.tag_id %></td>
        <td><%= link_to 'Show', product_category %></td>
        <td><%= link_to 'Edit', edit_product_category_path(product_category) %></td>
        <td><%= link_to 'Destroy', product_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Category', new_product_category_path %>

app/views/product_categories/new.html.erb
<h1>New Product Category</h1>

<%= render 'form', product_category: @product_category %>

<%= link_to 'Back', product_categories_path %>

app/views/product_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_category.name %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @product_category.tag_id %>
</p>

<%= link_to 'Edit', edit_product_category_path(@product_category) %> |
<%= link_to 'Back', product_categories_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :p_tag , "Tags(Saperated by commas)"%>
    <%= form.text_field :p_tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div style="float:right">
  <%= form_for(:filter_products, url: products_path , method: :get) do |form| %>
    <p> Filter based on catogary</p>
    <%= form.collection_select :catagory_id, ProductCategory.order(:name),:id,:name ,:prompt => "Select"%>
    <%= form.submit "Filter" %>
  <% end  %>
</div>




<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Tags</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr scope="row">
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.tags.map { |t| t.name }.join(",") %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @product.tags %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>